
import java.awt.event.ActionEvent;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author HP
 */
public class MyCalculatorframe extends javax.swing.JFrame {
    private String operator;
    private String firstNo;

    /**
     * Creates new form MyCalculatorframe
     */
    public MyCalculatorframe() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        noTextField = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        clearButton = new javax.swing.JButton();
        modButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        divbuttton = new javax.swing.JButton();
        onoffButton = new javax.swing.JToggleButton();
        jPanel3 = new javax.swing.JPanel();
        sevenButton = new javax.swing.JButton();
        eightButton = new javax.swing.JButton();
        nineButton = new javax.swing.JButton();
        multiplyButton = new javax.swing.JButton();
        powerButton = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        fourButton = new javax.swing.JButton();
        fiveButton = new javax.swing.JButton();
        sixButton = new javax.swing.JButton();
        substractButton = new javax.swing.JButton();
        sqrtButton = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        oneButton = new javax.swing.JButton();
        twoButton = new javax.swing.JButton();
        threeButtton = new javax.swing.JButton();
        addButton = new javax.swing.JButton();
        sqrButton = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        doublezeroButton = new javax.swing.JButton();
        zeroButton = new javax.swing.JButton();
        dotButton = new javax.swing.JButton();
        equalsButton = new javax.swing.JButton();
        plusminusButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(600, 500));
        getContentPane().setLayout(new java.awt.GridLayout(6, 1, 0, 10));

        jPanel1.setLayout(new java.awt.GridLayout(1, 4, 10, 0));

        noTextField.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        noTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noTextFieldActionPerformed(evt);
            }
        });
        jPanel1.add(noTextField);

        getContentPane().add(jPanel1);

        jPanel2.setLayout(new java.awt.GridLayout(1, 5, 10, 0));

        clearButton.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        clearButton.setText("CE");
        clearButton.setEnabled(false);
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });
        jPanel2.add(clearButton);

        modButton.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        modButton.setText("%");
        modButton.setEnabled(false);
        modButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modButtonActionPerformed(evt);
            }
        });
        jPanel2.add(modButton);

        backButton.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        backButton.setText("BACK");
        backButton.setEnabled(false);
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        jPanel2.add(backButton);

        divbuttton.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        divbuttton.setText("/");
        divbuttton.setEnabled(false);
        divbuttton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                divbutttonActionPerformed(evt);
            }
        });
        jPanel2.add(divbuttton);

        onoffButton.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        onoffButton.setText("ON");
        onoffButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onoffButtonActionPerformed(evt);
            }
        });
        jPanel2.add(onoffButton);

        getContentPane().add(jPanel2);

        jPanel3.setLayout(new java.awt.GridLayout(1, 5, 10, 0));

        sevenButton.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        sevenButton.setText("7");
        sevenButton.setEnabled(false);
        sevenButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sevenButtonActionPerformed(evt);
            }
        });
        jPanel3.add(sevenButton);

        eightButton.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        eightButton.setText("8");
        eightButton.setEnabled(false);
        eightButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eightButtonActionPerformed(evt);
            }
        });
        jPanel3.add(eightButton);

        nineButton.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        nineButton.setText("9");
        nineButton.setEnabled(false);
        nineButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nineButtonActionPerformed(evt);
            }
        });
        jPanel3.add(nineButton);

        multiplyButton.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        multiplyButton.setText("*");
        multiplyButton.setEnabled(false);
        multiplyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                multiplyButtonActionPerformed(evt);
            }
        });
        jPanel3.add(multiplyButton);

        powerButton.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        powerButton.setText("POW");
        powerButton.setEnabled(false);
        powerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                powerButtonActionPerformed(evt);
            }
        });
        jPanel3.add(powerButton);

        getContentPane().add(jPanel3);

        jPanel4.setLayout(new java.awt.GridLayout(1, 5, 10, 0));

        fourButton.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        fourButton.setText("4");
        fourButton.setEnabled(false);
        fourButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fourButtonActionPerformed(evt);
            }
        });
        jPanel4.add(fourButton);

        fiveButton.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        fiveButton.setText("5");
        fiveButton.setEnabled(false);
        fiveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fiveButtonActionPerformed(evt);
            }
        });
        jPanel4.add(fiveButton);

        sixButton.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        sixButton.setText("6");
        sixButton.setEnabled(false);
        sixButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sixButtonActionPerformed(evt);
            }
        });
        jPanel4.add(sixButton);

        substractButton.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        substractButton.setText("-");
        substractButton.setEnabled(false);
        substractButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                substractButtonActionPerformed(evt);
            }
        });
        jPanel4.add(substractButton);

        sqrtButton.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        sqrtButton.setText("SQRT");
        sqrtButton.setEnabled(false);
        sqrtButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sqrtButtonActionPerformed(evt);
            }
        });
        jPanel4.add(sqrtButton);

        getContentPane().add(jPanel4);

        jPanel5.setLayout(new java.awt.GridLayout(1, 5, 10, 0));

        oneButton.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        oneButton.setText("1");
        oneButton.setEnabled(false);
        oneButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oneButtonActionPerformed(evt);
            }
        });
        jPanel5.add(oneButton);

        twoButton.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        twoButton.setText("2");
        twoButton.setEnabled(false);
        twoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                twoButtonActionPerformed(evt);
            }
        });
        jPanel5.add(twoButton);

        threeButtton.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        threeButtton.setText("3");
        threeButtton.setEnabled(false);
        threeButtton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                threeButttonActionPerformed(evt);
            }
        });
        jPanel5.add(threeButtton);

        addButton.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        addButton.setText("+");
        addButton.setEnabled(false);
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });
        jPanel5.add(addButton);

        sqrButton.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        sqrButton.setText("SQR");
        sqrButton.setEnabled(false);
        sqrButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sqrButtonActionPerformed(evt);
            }
        });
        jPanel5.add(sqrButton);

        getContentPane().add(jPanel5);

        jPanel6.setLayout(new java.awt.GridLayout(1, 6, 10, 0));

        doublezeroButton.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        doublezeroButton.setText("00");
        doublezeroButton.setEnabled(false);
        doublezeroButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doublezeroButtonActionPerformed(evt);
            }
        });
        jPanel6.add(doublezeroButton);

        zeroButton.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        zeroButton.setText("0");
        zeroButton.setEnabled(false);
        zeroButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zeroButtonActionPerformed(evt);
            }
        });
        jPanel6.add(zeroButton);

        dotButton.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        dotButton.setText(".");
        dotButton.setEnabled(false);
        dotButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dotButtonActionPerformed(evt);
            }
        });
        jPanel6.add(dotButton);

        equalsButton.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        equalsButton.setText("=");
        equalsButton.setEnabled(false);
        equalsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                equalsButtonActionPerformed(evt);
            }
        });
        jPanel6.add(equalsButton);

        plusminusButton.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        plusminusButton.setText("+/-");
        plusminusButton.setEnabled(false);
        plusminusButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plusminusButtonActionPerformed(evt);
            }
        });
        jPanel6.add(plusminusButton);

        getContentPane().add(jPanel6);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void noTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_noTextFieldActionPerformed

    private void divbutttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_divbutttonActionPerformed
 setOperator(evt);        // TODO add your handling code here:
    }//GEN-LAST:event_divbutttonActionPerformed

    private void doublezeroButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doublezeroButtonActionPerformed
setNumber(evt);        // TODO add your handling code here:
    }//GEN-LAST:event_doublezeroButtonActionPerformed

    private void zeroButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zeroButtonActionPerformed
setNumber(evt);        // TODO add your handling code here:
    }//GEN-LAST:event_zeroButtonActionPerformed

    private void threeButttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_threeButttonActionPerformed
setNumber(evt);        // TODO add your handling code here:
    }//GEN-LAST:event_threeButttonActionPerformed

    private void twoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_twoButtonActionPerformed
setNumber(evt);        // TODO add your handling code here:
    }//GEN-LAST:event_twoButtonActionPerformed

    private void oneButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oneButtonActionPerformed
setNumber(evt);        // TODO add your handling code here:
    }//GEN-LAST:event_oneButtonActionPerformed

    private void sixButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sixButtonActionPerformed
       setNumber(evt); // TODO add your handling code here:
    }//GEN-LAST:event_sixButtonActionPerformed

    private void fiveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fiveButtonActionPerformed
setNumber(evt);        // TODO add your handling code here:
    }//GEN-LAST:event_fiveButtonActionPerformed

    private void fourButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fourButtonActionPerformed
setNumber(evt);        // TODO add your handling code here:
    }//GEN-LAST:event_fourButtonActionPerformed

    private void nineButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nineButtonActionPerformed
setNumber(evt);        // TODO add your handling code here:
    }//GEN-LAST:event_nineButtonActionPerformed

    private void eightButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eightButtonActionPerformed
setNumber(evt);        // TODO add your handling code here:
    }//GEN-LAST:event_eightButtonActionPerformed

    private void sevenButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sevenButtonActionPerformed
setNumber(evt);        // TODO add your handling code here:
    }//GEN-LAST:event_sevenButtonActionPerformed

    private void multiplyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_multiplyButtonActionPerformed
 setOperator(evt);        // TODO add your handling code here:
    }//GEN-LAST:event_multiplyButtonActionPerformed

    private void substractButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_substractButtonActionPerformed
 setOperator(evt);        // TODO add your handling code here:
    }//GEN-LAST:event_substractButtonActionPerformed

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
setOperator(evt);        // TODO add your handling code here:
    }//GEN-LAST:event_addButtonActionPerformed

    private void equalsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_equalsButtonActionPerformed
if(operator!=null&&!noTextField.getText().isEmpty())
        {
            String secondNo=noTextField.getText();
            switch(operator)
            {
                case "+":
                    try 
                    {
                        noTextField.setText(Integer.parseInt(firstNo)+Integer.parseInt(secondNo)+"");
                        
                    } 
                    catch (Exception e) 
                    {
                       noTextField.setText(Float.parseFloat(firstNo)+Float.parseFloat(secondNo)+""); 
                    }
                    
                    break;
               case "-":
                   try 
                    {
                        noTextField.setText(Integer.parseInt(firstNo)-Integer.parseInt(secondNo)+"");
                        
                    } 
                    catch (Exception e) 
                    {
                       noTextField.setText(Float.parseFloat(firstNo)-Float.parseFloat(secondNo)+""); 
                    }
                    
                    break;
               case "*":
                    try 
                    {
                        noTextField.setText(Integer.parseInt(firstNo)*Integer.parseInt(secondNo)+"");
                        
                    } 
                    catch (Exception e) 
                    {
                       noTextField.setText(Float.parseFloat(firstNo)*Float.parseFloat(secondNo)+""); 
                    }
                    
                    break;
               case "/":
                    try 
                    {
                        noTextField.setText(Integer.parseInt(firstNo)/Integer.parseInt(secondNo)+"");
                        
                    } 
                    catch (Exception e) 
                    {
                       noTextField.setText(Float.parseFloat(firstNo)/Float.parseFloat(secondNo)+""); 
                    }
                    
                    break;
                    case "%":
                    try 
                    {
                         noTextField.setText(Float.parseFloat(firstNo)*Float.parseFloat(secondNo)/100+"");   
                    } 
                    catch (Exception e) 
                    {
                       noTextField.setText(Float.parseFloat(firstNo)*Float.parseFloat(secondNo)/100+""); 
                    }
                    
                    break;
               
            }
        }        // TODO add your handling code here:
    }//GEN-LAST:event_equalsButtonActionPerformed

    private void modButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modButtonActionPerformed
        // TODO add your handling code here:
        setOperator(evt);
    }//GEN-LAST:event_modButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
        if(!noTextField.getText().isEmpty())
        {
            noTextField.setText(noTextField.getText().substring(0, noTextField.getText().length()-1));
            
        }
    }//GEN-LAST:event_backButtonActionPerformed

    private void dotButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dotButtonActionPerformed
        // TODO add your handling code here:
        if(!noTextField.getText().isEmpty())
        {
            noTextField.setText(("0."));
        }
        else if(noTextField.getText().contains("."))
        {
            noTextField.setText(noTextField.getText()+".");
        }
    }//GEN-LAST:event_dotButtonActionPerformed

    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
        // TODO add your handling code here:
        noTextField.setText("");
        operator=null;
        firstNo=null;
    }//GEN-LAST:event_clearButtonActionPerformed

    private void plusminusButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plusminusButtonActionPerformed
        // TODO add your handling code here:
        if(!noTextField.getText().isEmpty())
        {
            String no=noTextField.getText();
            try 
            {
                
                noTextField.setText((Long.parseLong(no)*-1)+"");
            } 
            catch (Exception e )    
            {
               noTextField.setText((Float.parseFloat(no)*-1)+"");  
            }
            
        }
        
    }//GEN-LAST:event_plusminusButtonActionPerformed

    private void sqrButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sqrButtonActionPerformed
        // TODO add your handling code here:
         String no=noTextField.getText();
         try 
         {
              noTextField.setText((Long.parseLong(no)*Long.parseLong(no))+"");  
            
        } 
          catch (Exception e) 
          {
             noTextField.setText((Float.parseFloat(no)*Float.parseFloat(no))+"");    
        }
       
    }//GEN-LAST:event_sqrButtonActionPerformed

    private void sqrtButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sqrtButtonActionPerformed
        // TODO add your handling code here:
        String no=noTextField.getText();
         try 
         {
              noTextField.setText(Math.sqrt(Long.parseLong(no))+"");  
            
        } 
          catch (Exception e) 
          {
             noTextField.setText(Math.sqrt(Float.parseFloat(no))+"");    
        }
        
    }//GEN-LAST:event_sqrtButtonActionPerformed

    private void powerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_powerButtonActionPerformed
        // TODO add your handling code here:
        String no=noTextField.getText();
         try 
         {
              noTextField.setText(Math.pow(Long.parseLong(no),Long.parseLong(no))+"");  
            
        } 
          catch (Exception e) 
          {
             noTextField.setText(Math.pow(Float.parseFloat(no),Float.parseFloat(no))+"");    
        }
    }//GEN-LAST:event_powerButtonActionPerformed

    private void onoffButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onoffButtonActionPerformed
        // TODO add your handling code here:
        if(onoffButton.isSelected())
        {
            onoffButton.setText("OFF");
            oneButton.setEnabled(true);
            twoButton.setEnabled(true);
           threeButtton.setEnabled(true);
            fourButton.setEnabled(true);
           fiveButton.setEnabled(true);
           sixButton.setEnabled(true);
            sevenButton.setEnabled(true);
            eightButton.setEnabled(true);
            nineButton.setEnabled(true);
           addButton.setEnabled(true);
            substractButton.setEnabled(true);
            multiplyButton.setEnabled(true);
            divbuttton.setEnabled(true);
           sqrButton.setEnabled(true);
            sqrtButton.setEnabled(true);
           powerButton.setEnabled(true);
           clearButton.setEnabled(true);
          backButton.setEnabled(true);
            equalsButton.setEnabled(true);
            dotButton.setEnabled(true);
            modButton.setEnabled(true);
           zeroButton.setEnabled(true);
           doublezeroButton.setEnabled(true);
            plusminusButton.setEnabled(true);
        }
        else
        {
            onoffButton.setText("ON");
            oneButton.setEnabled(false);
            twoButton.setEnabled(false);
           threeButtton.setEnabled(false);
            fourButton.setEnabled(false);
           fiveButton.setEnabled(false);
           sixButton.setEnabled(false);
            sevenButton.setEnabled(false);
            eightButton.setEnabled(false);
            nineButton.setEnabled(false);
           addButton.setEnabled(false);
            substractButton.setEnabled(false);
            multiplyButton.setEnabled(false);
            divbuttton.setEnabled(false);
           sqrButton.setEnabled(false);
            sqrtButton.setEnabled(false);
           powerButton.setEnabled(false);
           clearButton.setEnabled(false);
          backButton.setEnabled(false);
            equalsButton.setEnabled(false);
            dotButton.setEnabled(false);
            modButton.setEnabled(false);
            zeroButton.setEnabled(false);
           doublezeroButton.setEnabled(false);
            plusminusButton.setEnabled(false);
        }
    }//GEN-LAST:event_onoffButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MyCalculatorframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MyCalculatorframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MyCalculatorframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MyCalculatorframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
                new MyCalculatorframe().setVisible(true);
               }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JButton backButton;
    private javax.swing.JButton clearButton;
    private javax.swing.JButton divbuttton;
    private javax.swing.JButton dotButton;
    private javax.swing.JButton doublezeroButton;
    private javax.swing.JButton eightButton;
    private javax.swing.JButton equalsButton;
    private javax.swing.JButton fiveButton;
    private javax.swing.JButton fourButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JButton modButton;
    private javax.swing.JButton multiplyButton;
    private javax.swing.JButton nineButton;
    private javax.swing.JTextField noTextField;
    private javax.swing.JButton oneButton;
    private javax.swing.JToggleButton onoffButton;
    private javax.swing.JButton plusminusButton;
    private javax.swing.JButton powerButton;
    private javax.swing.JButton sevenButton;
    private javax.swing.JButton sixButton;
    private javax.swing.JButton sqrButton;
    private javax.swing.JButton sqrtButton;
    private javax.swing.JButton substractButton;
    private javax.swing.JButton threeButtton;
    private javax.swing.JButton twoButton;
    private javax.swing.JButton zeroButton;
    // End of variables declaration//GEN-END:variables
private void setNumber(ActionEvent evt)
    {
        String text=evt.getActionCommand();
        if(noTextField.getText().equals("")&&text.equals("00"))
        {
            
        }
        else if(noTextField.getText().equals("0"))
        {
            if(text.equals("00"))
            {
               noTextField.setText("0");
            }
            else
            {
               noTextField.setText(text); 
            }
            
           
        }
        else
        {
            noTextField.setText(noTextField.getText()+text);
        }
        
        
        
    }
    private void setOperator(ActionEvent evt)
    {
        if(noTextField.getText().isEmpty())
        {
            operator= null;
            firstNo=null;
        }
        else
        {
            operator=evt.getActionCommand();
            firstNo=noTextField.getText();
            noTextField.setText("");
        }
    }
}
